apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: your-app-db
  namespace: default
spec:
  allowedSourceRanges:
    - 0.0.0.0/0
  teamId: your-team
  volume:
    size: 5Gi
    storageClass: standard
  numberOfInstances: 3
  users:
    your-app-user:
      - superuser
      - createdb
  databases:
    your_database_name: your-app-user
  postgresql:
    version: "14"
    parameters:
      max_connections: "50"
      shared_buffers: "64MB"
      effective_cache_size: "192MB"
      work_mem: "1MB"
      maintenance_work_mem: "16MB"
      log_min_duration_statement: "1000"
      log_connections: "on"
      log_disconnections: "on"
  patroni:
    pg_hba:
      - host all all 0.0.0.0/0 trust
      - hostssl all all 0.0.0.0/0 trust
      - local all all trust
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
